### ISSUE TITLE
Expect blame info to appear on selected line

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph-git-extras#2] opened 2018-11-05 21:30 UTC
Currently, blame info only appears on lines where the blame information has changed from the previous line. The previous behavior was to show it on the selected line, which I found more useful.

![image](https://user-images.githubusercontent.com/754768/48027886-e0a49e80-e0fe-11e8-9f1a-af5cf048a779.png)

**Comment by chrismwendt** [comment] 2018-11-05 22:19
Extensions will need a way to determine which line is currently selected, or perhaps more generally where the cursor/selection is (similar to https://github.com/sourcegraph/sourcegraph-extension-api/issues/112)

**Comment by sqs** [comment] 2018-11-26 07:57
dupe of https://github.com/sourcegraph/sourcegraph/issues/1113

**Closed by sqs** 2018-11-26 07:57 UTC
